.TH "/home/jaca/Arduino/rawSend_mod/acFuncs.h" 3 "Fri Jul 27 2018" "AutomaS10-AC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jaca/Arduino/rawSend_mod/acFuncs.h \- Biblioteca de funcções para controlar o ar condicionado\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <IRLibSendBase\&.h>\fP
.br
\fC#include <IRLib_HashRaw\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRAW_DATA_LEN\fP   100"
.br
.RI "Tamanho do Array de Intervalos\&. "
.ti -1c
.RI "#define \fBMODULATION_FREQ\fP   39"
.br
.RI "Modulação do sinal em kHz\&. "
.ti -1c
.RI "#define \fBDELAY_INTERSIG\fP   4700"
.br
.RI "Intervalo entre envio de sinal (necessário para esse protocolo) em µs\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBacCommand\fP (IRsendRaw *sender, uint16_t sigArray[], char *msg)"
.br
.RI "Função de emissão de sinal padrão\&. "
.ti -1c
.RI "void \fBacLiga\fP (IRsendRaw sender)"
.br
.RI "Envia o sinal de ligar ar-condicionado\&. "
.ti -1c
.RI "void \fBacTempMax\fP (IRsendRaw sender)"
.br
.RI "Envia o sinal de temperatura Máxima, escolhido 25 graus C\&. "
.ti -1c
.RI "void \fBacTempMin\fP (IRsendRaw sender)"
.br
.RI "Envia o sinal de temperatura Minima, escolhido 18 graus C\&. "
.ti -1c
.RI "void \fBacTempMid\fP (IRsendRaw sender)"
.br
.RI "Envia o sinal de temperatura Média, escolhido 21 graus C\&. "
.ti -1c
.RI "void \fBacDesliga\fP (IRsendRaw sender)"
.br
.RI "Envia o sinal de desligar ar-condicionado\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const uint16_t \fBdesligaSig\fP [\fBRAW_DATA_LEN\fP]"
.br
.RI "Sinal de desliga simples\&. "
.ti -1c
.RI "const uint16_t \fBliga21Sig\fP [\fBRAW_DATA_LEN\fP]"
.br
.RI "Sinal de liga em 21 graus\&. "
.ti -1c
.RI "const uint16_t \fBtemp18\fP [\fBRAW_DATA_LEN\fP]"
.br
.RI "Sinal de temperatura 18 graus\&. "
.ti -1c
.RI "const uint16_t \fBtemp21\fP [\fBRAW_DATA_LEN\fP]"
.br
.RI "Sinal de temperatura 21 graus\&. "
.ti -1c
.RI "const uint16_t \fBtemp25\fP [\fBRAW_DATA_LEN\fP]"
.br
.RI "Sinal de temperatura 25 graus\&. "
.in -1c
.SH "Detailed Description"
.PP 
Biblioteca de funcções para controlar o ar condicionado\&. 

Biblioteca contendo funções de envio de sinal para o ar condicionado no Laboratório de Hardware no Labotec 3 da UEFS\&.
.br
Os sinais são de funções principais escohidas parafornecer suporte básico de controle\&. 
.PP
\fBAuthor:\fP
.RS 4
jaca 
.RE
.PP
\fBDate:\fP
.RS 4
14/07/2018 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void acCommand (IRsendRaw * sender, uint16_t sigArray[], char * msg)"

.PP
Função de emissão de sinal padrão\&. Emite o sinal passado em sigArray[] usando o sender e as constantes padrão de tamanho do sinal e frequencia de modulação\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIRsendRaw\fP * sender - Objeto de envio de sinal da biblioteca IRlib2 
.br
\fIuint16_t\fP sigArray[] - Array de intercvalos do Sinal 
.br
\fIchar\fP * msg - Mensagem de saída Serial 
.RE
.PP
\fBPrecondition:\fP
.RS 4
- 
.RE
.PP
\fBPostcondition:\fP
.RS 4
- 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void acDesliga (IRsendRaw sender)"

.PP
Envia o sinal de desligar ar-condicionado\&. Usa o objeto sender para enviar um sinal de desligar o ar-condicionado\&.
.br
O sinal foi capturado diretamente do controle remoto do ar-condicionado instalado\&.
.br
Não é possivel configurar esse sinal\&.
.br
\fBParameters:\fP
.RS 4
\fIIRsendRaw\fP sender - Objeto de envio de sinal cru para o pino 3, invariavelmente 
.RE
.PP
\fBPrecondition:\fP
.RS 4
- 
.RE
.PP
\fBPostcondition:\fP
.RS 4
- 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void acLiga (IRsendRaw sender)"

.PP
Envia o sinal de ligar ar-condicionado\&. Envia o sinal de ligar o ar-condicionado em 21 graus e no modo Cool\&.
.br
O sinal foi capturado diretamente do controle remoto do aparelho no modo Cool, ṕara resfriamento e em 21 graus de tempereatura, sem swing das paletas\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIRsendRaw\fP sender - Objeto de envio de sinal cru para o pino 3, invariavelmente 
.RE
.PP
\fBPrecondition:\fP
.RS 4
- 
.RE
.PP
\fBPostcondition:\fP
.RS 4
- 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void acTempMax (IRsendRaw sender)"

.PP
Envia o sinal de temperatura Máxima, escolhido 25 graus C\&. Envia o sinal de temperatura de 25 graus para o aparelho de ar-condicionado\&.
.br
Independe de modo\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIRsendRaw\fP sender - Objeto de envio de sinal cru para o pino 3, invariavelmente 
.RE
.PP
\fBPrecondition:\fP
.RS 4
- 
.RE
.PP
\fBPostcondition:\fP
.RS 4
- 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void acTempMid (IRsendRaw sender)"

.PP
Envia o sinal de temperatura Média, escolhido 21 graus C\&. Envia o sinal de temperatura de 21 graus para o aparelho de ar-condicionado\&.
.br
Independe de modo 
.PP
\fBParameters:\fP
.RS 4
\fIIRsendRaw\fP sender - Objeto de envio de sinal cru para o pino 3, invariavelmente 
.RE
.PP
\fBPrecondition:\fP
.RS 4
- 
.RE
.PP
\fBPostcondition:\fP
.RS 4
- 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void acTempMin (IRsendRaw sender)"

.PP
Envia o sinal de temperatura Minima, escolhido 18 graus C\&. Envia o sinal de temperatura de 18 graus para o aparelho de ar-condicionado\&.
.br
Independe de modo\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIRsendRaw\fP sender - Objeto de envio de sinal cru para o pino 3, invariavelmente 
.RE
.PP
\fBPrecondition:\fP
.RS 4
- 
.RE
.PP
\fBPostcondition:\fP
.RS 4
- 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "const uint16_t desligaSig[\fBRAW_DATA_LEN\fP]"
\fBInitial value:\fP
.PP
.nf
{
  4538, 4377, 638,  1533, 638,  466,  638,  1520, 638,  1529,
  638,  458,  638,  456,  638,  1529, 638,  461,  638,  453,
  638,  1530, 638,  461,  638,  461,  638,  1538, 638,  1523,
  638,  459,  638,  1530, 638,  463,  638,  1523, 638,  1520,
  638,  1522, 638,  1522, 638,  458,  638,  1530, 638,  1519,
  638,  1531, 638,  453,  638,  458,  638,  466,  638,  461,
  638,  1520, 638,  461,  638,  459,  638,  1532, 638,  1519,
  638,  1523, 638,  450,  638,  466,  638,  466,  638,  453,
  638,  458,  638,  466,  638,  458,  638,  461,  638,  1522,
  638,  1520, 638,  1519, 638,  1538, 638,  1517, 638,  1000
}
.fi
.PP
Sinal de desliga simples\&. 
.SS "const uint16_t liga21Sig[\fBRAW_DATA_LEN\fP]"
\fBInitial value:\fP
.PP
.nf
{
  4550, 4376, 638,  1543, 638,  466,  638,  1521, 638,  1523,
  638,  466,  638,  450,  638,  1523, 638,  466,  638,  450,
  638,  1538, 638,  456,  638,  457,  638,  1520, 638,  1516,
  638,  466,  638,  1538, 638,  1528, 638,  450,  638,  1538,
  638,  1522, 638,  1523, 638,  1524, 638,  1520, 638,  1516,
  638,  466,  638,  1538, 638,  450,  638,  466,  638,  466,
  638,  498,  638,  466,  638,  466,  638,  470,  638,  1524,
  638,  1520, 638,  466,  638,  456,  638,  456,  638,  450,
  638,  466,  638,  1524, 638,  453,  638,  466,  638,  1521,
  638,  1523, 638,  1524, 638,  1520, 638,  1524, 638,  1000
}
.fi
.PP
Sinal de liga em 21 graus\&. 
.SS "const uint16_t temp18[\fBRAW_DATA_LEN\fP]"
\fBInitial value:\fP
.PP
.nf
{
  4550, 4379, 638,  1525, 638,  466,  638,  1524, 638,  1520,
  638,  466,  638,  450,  638,  1538, 638,  466,  638,  450,
  638,  1523, 638,  466,  638,  457,  638,  1524, 638,  1520,
  638,  466,  638,  1522, 638,  1543, 638,  456,  638,  1538,
  638,  1520, 638,  1521, 638,  1523, 638,  1538, 638,  1519,
  638,  466,  638,  1521, 638,  456,  638,  466,  638,  450,
  638,  456,  638,  466,  638,  453,  638,  474,  638,  492,
  638,  450,  638,  1523, 638,  466,  638,  466,  638,  453,
  638,  457,  638,  1538, 638,  1520, 638,  1524, 638,  450,
  638,  1538, 638,  1542, 638,  1522, 638,  1538, 638,  1000
}
.fi
.PP
Sinal de temperatura 18 graus\&. 
.SS "const uint16_t temp21[\fBRAW_DATA_LEN\fP]"
\fBInitial value:\fP
.PP
.nf
{
  4550, 4378, 638,  1532, 638,  456,  638,  1525, 638,  1538,
  638,  466,  638,  466,  638,  1523, 638,  457,  638,  469,
  638,  1525, 638,  457,  638,  453,  638,  1522, 638,  1538,
  638,  466,  638,  1538, 638,  1528, 638,  469,  638,  1525,
  638,  1525, 638,  1538, 638,  1538, 638,  1523, 638,  1519,
  638,  457,  638,  1532, 638,  457,  638,  453,  638,  456,
  638,  457,  638,  456,  638,  453,  638,  469,  638,  1538,
  638,  1522, 638,  469,  638,  456,  638,  456,  638,  469,
  638,  456,  638,  1522, 638,  456,  638,  456,  638,  1525,
  638,  1538, 638,  1523, 638,  1522, 638,  1522, 638,  1000
}
.fi
.PP
Sinal de temperatura 21 graus\&. 
.SS "const uint16_t temp25[\fBRAW_DATA_LEN\fP]"
\fBInitial value:\fP
.PP
.nf
{
  4550, 4380, 638,  1528, 638,  466,  638,  1522, 638,  1523,
  638,  466,  638,  450,  638,  1523, 638,  466,  638,  450,
  638,  1538, 638,  450,  638,  466,  638,  1525, 638,  1522,
  638,  466,  638,  1519, 638,  1541, 638,  466,  638,  1525,
  638,  1519, 638,  1516, 638,  1538, 638,  1522, 638,  1522,
  638,  466,  638,  1519, 638,  466,  638,  466,  638,  450,
  638,  456,  638,  457,  638,  466,  638,  1538, 638,  1541,
  638,  466,  638,  466,  638,  453,  638,  457,  638,  466,
  638,  466,  638,  466,  638,  450,  638,  1522, 638,  1522,
  638,  1538, 638,  1519, 638,  1538, 638,  1522, 638,  1000
}
.fi
.PP
Sinal de temperatura 25 graus\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for AutomaS10-AC from the source code\&.
