.TH "md__home_jaca_Arduino_rawSend_mod_README" 3 "Sun Jul 22 2018" "AutomaS10-AC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_jaca_Arduino_rawSend_mod_READMEAutoma S10 - Ar-condicionado 
 \- Biblioteca contendo funções para transmissão de sinais de controle para o ar-condicionado do Laboratório S10\&.
.PP
As funções foram baseadas nos comandos capturados diretamente do controle remoto do ar-condicionado instalado no Laboratório S10, e contemplam o básico necessário para um controle razoável, essas funções incluem ligar e desligar o dispositivo, e selecionar 3 temperaturas previamente programadas, escolidas por serem geralmente escolhidas no uso comum do dia-a-dia\&. 
